AWSTemplateFormatVersion: 2010-09-09
Description: ECS Cluster Template for CloudFormation Demo. 

#Metadata:

Parameters:
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
#Mappings:

#Conditions:

Resources:
  #ECS Cluster for Frontend
  FrontendECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${StackPrefix}-Frontend-Cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-Frontend-Cluster
  #ECS Cluster for Backend
  BackendECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${StackPrefix}-Backtend-Cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-Backend-Cluster
  #ECS Cluster for Batch
  BatchECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${StackPrefix}-Batch-Cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-Batch-Cluster
Outputs:
  FrontendECSCluster:
    Description: Frontend ECS Cluster ID
    Value: !Ref FrontendECSCluster
    Export:
      Name: !Sub ${StackPrefix}-Frontend-ECSCluster
  FrontendECSClusterName:
    Description: Frontend ECS Cluster Name
    Value: !Sub ${StackPrefix}-Frontend-Cluster
    Export:
      Name: !Sub ${StackPrefix}-Frontend-ECSCluster-Name
  BackendECSCluster:
    Description: Backend ECS Cluster ID
    Value: !Ref BackendECSCluster
    Export:
      Name: !Sub ${StackPrefix}-Backend-ECSCluster
  BackendECSClusterName:
    Description: Backend ECS Cluster Name
    Value: !Sub ${StackPrefix}-Backtend-Cluster
    Export:
      Name: !Sub ${StackPrefix}-Backend-ECSCluster-Name
  BatchECSCluster:
    Description: Batch ECS Cluster ID
    Value: !Ref BatchECSCluster
    Export:
      Name: !Sub ${StackPrefix}-Batch-ECSCluster
  BatchECSClusterName:
    Description: Batch ECS Cluster Name
    Value: !Sub ${StackPrefix}-Batch-Cluster
    Export:
      Name: !Sub ${StackPrefix}-Batch-ECSCluster-Name      